
spring:
  application:
    name: quartz-demo-test

  thymeleaf:
      cache: false

#################数据库#################
#因为要使用log4jdbc作为数据库驱动，所以数据配置文件也需要做相应的改动
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://?characterEncoding=utf-8
#需要由原来的配置改为
#spring.datasource.driver-class-name=net.sf.log4jdbc.DriverSpy
#spring.datasource.url=jdbc:log4jdbc:mysql://host:port/dbname?characterEncoding=utf-8
  datasource:
    type: com.tinxi.common.datasource.CommonDruidDataSource
#    driver-class-name: net.sf.log4jdbc.DriverSpy
#    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/tinxi_demo?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8
#    url: jdbc:log4jdbc:mysql://192.168.52.219:3306/tinxi_demo?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.52.219:3306/tinxi_demo?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/quartz_data?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8
# 本地mysql
    username: root
    password: 123456
    # 虚拟机192.168.52.219
#    username: root
#    password: root@2019
#    initialSize: 0
#    maxActive: 20
#    minIdle: 0
#    maxWait: 60000

    # oracle 数据库配置
#    type: cn.csatv.common.db.datasource.CommonDruidDataSource
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@192.168.52.222:1521:helowin #本地虚拟机docker数据库
#    username: tinxi
#    password: 123
#    url: jdbc:oracle:thin:@114.116.187.185:1521:orcl #华为云服务器
#    username: cucc_audit
#    password: Cuc_2019
    initialSize: 0
    maxActive: 20
    minIdle: 0
    maxWait: 60000
    validation-query: select 1 from dual